# Generated by Django 3.2.9 on 2021-12-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='ideas/audio/'),
        ),
    ]
